# Site settings
# See default settings at https://jekyllrb.com/docs/configuration/#default-configuration
title: Yash Mehrotra
description: Learning Distributed Systems and Preparing for Technical Interviews

baseurl: ""
permalink: post/:title

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

# Custom variables
author: Yash Mehrotra

social:
  github: YashMeh
  twitter: YashMeh29715504
  linkedin: yash-mehrotra-ab2573154
  email: mehrotra.yash9@gmail.com

google_analytics: "UA-169929112-1"
