# Site settings
# See default settings at https://jekyllrb.com/docs/configuration/#default-configuration
title: Yash Mehrotra
description: You have to die a few times before you can actually live

baseurl: ""
permalink: post/:title

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 3

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Download Resume
    url: https://drive.google.com/file/d/1VzRaW6toF2uEUxbnVw8NQCFb43cQulq_/view

# Custom variables
author: Yash Mehrotra

social:
  github: YashMeh
  twitter: YashMeh29715504
  linkedin: yash-mehrotra-ab2573154
  email: mehrotra.yash9@gmail.com

google_analytics: "UA-169929112-1"
disqus:
  shortname: my-disqus-shortname
